version: '3'

#########################################################
####                       SSH                       ####
#########################################################

#########################################################
####                   Networking                    ####
#########################################################
networks:
  ssh_net:
    driver: bridge

#########################################################
####                   Volumes                       ####
#########################################################
volumes:
  ssh_data: {}

#########################################################
####                   Services                      ####
#########################################################
services:

  # SSH server
  ssh:
    build: balluff/ssh
    container_name: blf_ssh
    volumes:
      - ssh_data:/home/
    restart: always
    expose:
      - 22
    networks:
      - ssh_net