version: '3'

#########################################################
####                       SSH                       ####
#########################################################

#########################################################
####                   Networking                    ####
#########################################################
networks:
  ssh_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 171.6.0.0/24

#########################################################
####                   Volumes                       ####
#########################################################
volumes:
  ssh_data: {}

#########################################################
####                   Services                      ####
#########################################################

services:

  # SSH SUT client
  sut:
    build: test
    container_name: sut_ssh
    depends_on:
      - blf_ssh
    volumes:
      - ssh_data:/tmp/
    networks:
      ssh_net:
        ipv4_address: 171.6.0.20

  # SSH server
  blf_ssh:
    build: x86_64
    container_name: blf_ssh
    volumes:
      - ssh_data:/tmp/
    expose:
      - 22
    networks:
      ssh_net:
        ipv4_address: 171.6.0.10